[package]
name = "phoenix-seat-manager-common"
version = "0.1.1"
edition = "2021"
repository = "https://github.com/Ellipsis-Labs/phoenix-seat-manager-v1"
authors = ["Ellipsis Labs <maintainers@ellipsislabs.xyz>"]
description = "Automatic seat manager for the Phoenix program"
license-file = "LICENSE"

[lib]
crate-type = ["cdylib", "lib"]
name = "phoenix_seat_manager"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
test = []

[profile.release]
lto = "fat"
codegen-units = 1
overflow-checks = true

[dependencies]
phoenix-common = {git = "https://github.com/florian-klein/phoenix-v1.git", branch = "crate", features = ["no-entrypoint"]}
shank = "*"
lib-sokoban =  "*"
itertools = "*"
static_assertions = "*"
spl-token = { version = "*", features = ["no-entrypoint"] }
spl-associated-token-account = { version = "*", features = [ "no-entrypoint" ] } 
toml_edit = "*"
proc-macro-crate = "*"
solana-program = "*"
borsh = "*"
bytemuck = "*"
num_enum = "*"

[dev-dependencies]
rand = "0.7.3"
